// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQTsXm3hbsZrUpUMi0eLghT_8PD93BpOg',
    appId: '1:608669539737:web:9c9bc6ea834d6c14c94708',
    messagingSenderId: '608669539737',
    projectId: 'vowly-896b9',
    authDomain: 'vowly-896b9.firebaseapp.com',
    storageBucket: 'vowly-896b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ak1WEaDbQjMXo9_sxUm3y391XnWMVGU',
    appId: '1:608669539737:android:706ebf26bbdeed2ec94708',
    messagingSenderId: '608669539737',
    projectId: 'vowly-896b9',
    storageBucket: 'vowly-896b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57xxIJn7X7jmbipQGPIT_PiHQknezeg4',
    appId: '1:608669539737:ios:05e94e137b8d03f3c94708',
    messagingSenderId: '608669539737',
    projectId: 'vowly-896b9',
    storageBucket: 'vowly-896b9.firebasestorage.app',
    iosBundleId: 'com.example.vowlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57xxIJn7X7jmbipQGPIT_PiHQknezeg4',
    appId: '1:608669539737:ios:05e94e137b8d03f3c94708',
    messagingSenderId: '608669539737',
    projectId: 'vowly-896b9',
    storageBucket: 'vowly-896b9.firebasestorage.app',
    iosBundleId: 'com.example.vowlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQTsXm3hbsZrUpUMi0eLghT_8PD93BpOg',
    appId: '1:608669539737:web:b32d3856baac24bdc94708',
    messagingSenderId: '608669539737',
    projectId: 'vowly-896b9',
    authDomain: 'vowly-896b9.firebaseapp.com',
    storageBucket: 'vowly-896b9.firebasestorage.app',
  );
}
